# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "AppStoreTutorial.xcodeproj")
    build_app(scheme: "AppStoreTutorial")
    upload_to_app_store
  end

  desc "Sync local metadata to App Store Connect"
  lane :sync_metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true,
      overwrite_screenshots: false
    )
  end

  desc "Sync local metadata and screenshots to App Store Connect"
  lane :sync_all_metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      force: true,
      overwrite_screenshots: true
    )
  end
end
